src/AppBundle/Entity/Review.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Review
 *
 * @ORM\Table(name="tblReview")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ReviewRepository")
 */
class Review
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=100, nullable=false)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="text", type="text", nullable=false)
     */
    private $text;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", nullable=false)
     */
    private $email;

    /**
     * @var bool
     *
     * @ORM\Column(name="isActive", type="boolean")
     */
    private $isActive = false;

    /**
     * @var bool
     *
     * @ORM\Column(name="isRemove", type="boolean")
     */
    private $isRemove = false;

    /**
     * @var \Datetime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @param string $name
     * @param string $email
     * @param string $text
     */
    public function __construct(string $name, string $email, string $text)
    {
        $this->name = $name;
        $this->email = $email;
        $this->text = $text;
        $this->createdAt =  new \Datetime();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getText(): string
    {
        return $this->text;
    }

    /**
     * @param string $text
     */
    public function setText(string $text): void
    {
        $this->text = $text;
    }

    /**
     * @return string
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * @return bool
     */
    public function isActive(): bool
    {
        return $this->isActive;
    }

    /**
     * @param bool $isActive
     */
    public function setIsActive(bool $isActive): void
    {
        $this->isActive = $isActive;
    }

    /**
     * @return bool
     */
    public function isRemove(): bool
    {
        return $this->isRemove;
    }

    /**
     * @param bool $isRemove
     */
    public function setIsRemove(bool $isRemove): void
    {
        $this->isRemove = $isRemove;
    }

    /**
     * @return \Datetime
     */
    public function getCreatedAt(): \Datetime
    {
        return $this->createdAt;
    }

    /**
     * @param \Datetime $createdAt
     */
    public function setCreatedAt(\Datetime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }
}

src/AppBundle/Controller/HomeController.php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use AppBundle\Entity\CallRequest;
use AppBundle\Entity\Review;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class HomeController extends Controller
{
    public function callListAction()
    {
        $calls = $this->getDoctrine()->getRepository(CallRequest::class)->findBy([
            'isActive' => false
        ]);

        return $this->render('@app/Home/index.html.twig', [
            'calls' => $calls
        ]);
    }

    public function callConfirmAction(CallRequest $callRequest)
    {
        $callRequest->setIsActive(true);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('admin_call_requests');
    }

    public function callUnconfirmAction(CallRequest $callRequest)
    {
        $callRequest->setIsActive(false);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('admin_call_requests');
    }

    /**
     * @param Request $request
     *
     * @return Response
     */
    public function reviewListAction(Request $request): Response
    {
        $paginator = $this->get('knp_paginator');
        $reviews = $this->getDoctrine()
            ->getRepository(Review::class)
            ->getAllReviewsQuery();
        $pagination = $paginator->paginate($reviews, $request->get('page', 1), 20);

        return $this->render('@app/Home/reviews.html.twig', [
            'reviews' => $pagination
        ]);
    }

    public function reviewConfirmAction(Review $review)
    {
        $review->setIsActive(true);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('admin_reviews');
    }

    public function reviewUnconfirmAction(Review $review)
    {
        $review->setIsActive(false);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('admin_reviews');
    }

    public function reviewRemoveAction(Review $review)
    {
        $review->setIsRemove(true);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('admin_reviews');
    }

    public function indexAction()
    {
        return $this->render('@desktop/index.html');
    }
}

src/AppBundle/Resources/views/Home/index.html.twig
{% extends '@app/admin_base.html.twig' %}
{% block title %}
  Запросы на вызов
{% endblock %}
{% block content %}
  <div class="panel">
    <div class="panel-heading panel-primary">
      <h3>
        Запросы на вызов ({{ callRequests.getTotalItemCount }})
      </h3>
    </div>

    <div class="panel-body">
      {% if callRequests.getTotalItemCount %}
        <div class="table-responsive table-padding-85" style="padding-bottom: 150px">
          <table class="table table-hover table-striped">
            <thead>
            <tr class="bg-primary">
              <th>{{ knp_pagination_sortable(callRequests, 'ID', ['cr.id']) }}</th>
              <th>{{ knp_pagination_sortable(callRequests, 'Телефон', ['cr.phone']) }}</th>
              <th>{{ knp_pagination_sortable(callRequests, 'Имя', ['cr.name']) }}</th>
              <th>{{ knp_pagination_sortable(callRequests, 'Дата', ['cr.createdAt']) }}</th>
              <th>{{ knp_pagination_sortable(callRequests, 'Статус', ['cr.isActive']) }}</th>
              <th>Действия</th>
            </tr>
            </thead>

            <tbody>
            {% for callRequest in callRequests %}
              <tr>
                <td>{{ callRequest.id }}</td>
                <td>{{ callRequest.phone }}</td>
                <td>{{ callRequest.name }}</td>
                <td>{{ callRequest.createdAt | date("d/m/Y H:i:s") }}</td>
                <td>
                  {% if callRequest.active %}
                    <div class="label label-success">
                      Обработан
                    </div>
                  {% else %}
                    <div class="label label-danger">
                      Необработан
                    </div>
                  {% endif %}
                </td>
                <td>
                  <ul class="icons-list">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-menu9"></i>
                      </a>

                      <ul class="dropdown-menu dropdown-menu-right">
                        {% if callRequest.active %}
                          <li>
                            <a
                              href="{{ path('admin_call_unconfirm', {'id': callRequest.getId}) }}">
                              <i class="icon-plus3 text-blue"></i>

                              Не обработан
                            </a>
                          </li>
                        {% else %}
                          <li>
                            <a href="{{ path('admin_call_confirm', {'id': callRequest.getId}) }}">
                              <i class="icon-plus3 text-blue"></i>

                              Обработан
                            </a>
                          </li>
                        {% endif %}
                      </ul>
                    </li>
                  </ul>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        {% if callRequests.getTotalItemCount >= 20 %}
          <div class="panel-body">
            <div class="text-center">
              {{ knp_pagination_render(callRequests) }}
            </div>
          </div>
        {% endif %}
      {% else %}
        <div class="panel panel-body">
          <div class="text-center">
            У вас нет запросов на вызов
          </div>
        </div>
      {% endif %}
    </div>
  </div>

  <style>
    th a {
      color: white;
    }
  </style>
{% endblock %}

src/AppBundle/Resources/views/Home/reviews.html.twig
{% extends '@app/admin_base.html.twig' %}
{% block title %}
  Отзывы
{% endblock %}

{% block content %}
  <div class="panel">
    <div class="panel-heading panel-primary">
      <h3>
        Отзывы ({{ reviews.getTotalItemCount }})
      </h3>
    </div>

    <div class="panel-body">
      {% if reviews.getTotalItemCount %}
        <div class="table-responsive table-padding-85" style="padding-bottom: 150px">
          <table class="table table-hover table-striped">
            <thead>
            <tr class="bg-primary">
              <th>{{ knp_pagination_sortable(reviews, 'ID', ['cr.id']) }}</th>
              <th>{{ knp_pagination_sortable(reviews, 'Имя', ['cr.name']) }}</th>
              <th>{{ knp_pagination_sortable(reviews, 'Email', ['cr.email']) }}</th>
              <th>{{ knp_pagination_sortable(reviews, 'Дата', ['cr.createdAt']) }}</th>
              <th>{{ knp_pagination_sortable(reviews, 'Статус', ['cr.isActive']) }}</th>
              <th>Действия</th>
            </tr>
            </thead>

            <tbody>
            {% for review in reviews %}
              <tr>
                <td>{{ review.id }}</td>
                <td>{{ review.name }}</td>
                <td>{{ review.email }}</td>
                <td>{{ review.createdAt | date("d/m/Y H:i:s") }}</td>
                <td>
                  {% if review.active %}
                    <div class="label label-success">
                      Обработан
                    </div>
                  {% else %}
                    <div class="label label-danger">
                      Необработан
                    </div>
                  {% endif %}
                </td>
                <td>
                  <ul class="icons-list">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-menu9"></i>
                      </a>

                      <ul class="dropdown-menu dropdown-menu-right">
                        {% if review.active %}
                          <li>
                            <a
                              href="{{ path('admin_review_unconfirm', {'id': review.getId}) }}">
                              <i class="icon-plus3 text-blue"></i>

                              Не обработан
                            </a>
                          </li>
                        {% else %}
                          <li>
                            <a href="{{ path('admin_review_confirm', {'id': review.getId}) }}">
                              <i class="icon-plus3 text-blue"></i>

                              Обработан
                            </a>
                          </li>
                        {% endif %}

                        <li>
                          <a href="{{ path('admin_review_remove', {'id': review.getId}) }}">
                            <i class="icon-pencil text-danger"></i>

                            Удалить
                          </a>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        {% if reviews.getTotalItemCount >= 20 %}
          <div class="panel-body">
            <div class="text-center">
              {{ knp_pagination_render(reviews) }}
            </div>
          </div>
        {% endif %}
      {% else %}
        <div class="panel panel-body">
          <div class="text-center">
            У вас нет отзывов
          </div>
        </div>
      {% endif %}
    </div>
  </div>

  <style>
    th a {
      color: white;
    }
  </style>
{% endblock %}